"""initial migration

Revision ID: e1a7a3094a3c
Revises: 
Create Date: 2023-04-21 17:45:05.627585

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e1a7a3094a3c'
down_revision = None
branch_labels = None
depends_on = None

def drop_if_exists(table_name):
    if op.get_context().dialect.has_table(op.get_context().bind, table_name):
        op.drop_table(table_name)

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Define a list of table names to drop
    drop_if_exists('reviews')
    drop_if_exists('cities')
    drop_if_exists('amenities')
    drop_if_exists('states')
    drop_if_exists('users')
    drop_if_exists('place_amenity')
    with op.batch_alter_table('places', schema=None) as batch_op:
        batch_op.add_column(sa.Column('city_id', sa.String(length=60), nullable=False))
        batch_op.add_column(sa.Column('user_id', sa.String(length=60), nullable=False))
        batch_op.alter_column('id',
               existing_type=mysql.VARCHAR(length=60),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True)
        batch_op.drop_column('number_bathrooms')
        batch_op.drop_column('longitude')
        batch_op.drop_column('max_guest')
        batch_op.drop_column('latitude')
        batch_op.drop_column('description')
        batch_op.drop_column('price_by_night')
        batch_op.drop_column('updated_at')
        batch_op.drop_column('number_rooms')
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('places', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', mysql.DATETIME(), nullable=False))
        batch_op.add_column(sa.Column('number_rooms', mysql.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('updated_at', mysql.DATETIME(), nullable=False))
        batch_op.add_column(sa.Column('price_by_night', mysql.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('description', mysql.VARCHAR(length=128), nullable=True))
        batch_op.add_column(sa.Column('latitude', mysql.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('max_guest', mysql.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('longitude', mysql.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('number_bathrooms', mysql.INTEGER(), autoincrement=False, nullable=False))
        batch_op.alter_column('id',
               existing_type=sa.Integer(),
               type_=mysql.VARCHAR(length=60),
               existing_nullable=False,
               autoincrement=True)
        batch_op.drop_column('user_id')
        batch_op.drop_column('city_id')

    op.create_table('place_amenity',
    sa.Column('place_id', mysql.VARCHAR(length=60), nullable=False),
    sa.Column('amenity_id', mysql.VARCHAR(length=60), nullable=False),
    sa.ForeignKeyConstraint(['amenity_id'], ['amenities.id'], name='place_amenity_ibfk_2'),
    sa.ForeignKeyConstraint(['place_id'], ['places.id'], name='place_amenity_ibfk_1'),
    sa.PrimaryKeyConstraint('place_id', 'amenity_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('users',
    sa.Column('id', mysql.VARCHAR(length=60), nullable=False),
    sa.Column('created_at', mysql.DATETIME(), nullable=False),
    sa.Column('updated_at', mysql.DATETIME(), nullable=False),
    sa.Column('email', mysql.VARCHAR(length=128), nullable=False),
    sa.Column('password', mysql.VARCHAR(length=128), nullable=False),
    sa.Column('first_name', mysql.VARCHAR(length=128), nullable=True),
    sa.Column('last_name', mysql.VARCHAR(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('states',
    sa.Column('id', mysql.VARCHAR(length=60), nullable=False),
    sa.Column('created_at', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('name', mysql.VARCHAR(length=128), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.create_table('amenities',
    sa.Column('id', mysql.VARCHAR(length=60), nullable=False),
    sa.Column('created_at', mysql.DATETIME(), nullable=False),
    sa.Column('updated_at', mysql.DATETIME(), nullable=False),
    sa.Column('name', mysql.VARCHAR(length=128), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('cities',
    sa.Column('id', mysql.VARCHAR(length=60), nullable=False),
    sa.Column('created_at', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('name', mysql.VARCHAR(length=128), nullable=False),
    sa.Column('state_id', mysql.VARCHAR(length=60), nullable=False),
    sa.ForeignKeyConstraint(['state_id'], ['states.id'], name='cities_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.create_table('reviews',
    sa.Column('id', mysql.VARCHAR(length=60), nullable=False),
    sa.Column('created_at', mysql.DATETIME(), nullable=False),
    sa.Column('updated_at', mysql.DATETIME(), nullable=False),
    sa.Column('place_id', mysql.VARCHAR(length=60), nullable=False),
    sa.Column('user_id', mysql.VARCHAR(length=60), nullable=False),
    sa.Column('text', mysql.VARCHAR(length=1024), nullable=False),
    sa.ForeignKeyConstraint(['place_id'], ['places.id'], name='reviews_ibfk_1'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='reviews_ibfk_2'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
